if (!require(ggplot2)) 
  install.packages('ggplot2')
library(ggplot2)
if (!require(GGally)) 
  install.packages('GGally')
library(GGally)
if (!require(psych)) 
  install.packages('psych')
library(psych)
if (!require(ggiraph)) 
  install.packages('ggiraph')
library(ggiraph)
if (!require(ggiraphExtra)) 
  install.packages('ggiraphExtra')
library(ggiraphExtra)
if (!require(dplyr)) 
  install.packages('dplyr')
library(dplyr)
